apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-juso-deployment
  labels:
    app: node-juso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-juso
  template:
    metadata:
      labels:
        app: node-juso 
    spec:
      containers:
      - name: node-juso
        image: docker.io/cybaj/node-juso:withJusoApi0.4
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: node-juso-api-key
